'use strict';
const CC_BRAND={logo:'assets/cc-logo.avif',tagline:'ROLL UP READY FOR BUSINESS',colors:{forest:'#0F3D2E',deep:'#08281F',cream:'#F7EBD0',light:'#FFF6E0',yellow:'#FFC629',red:'#D62828',sage:'#3A6B4F'},headline:'Georgia,serif',body:'Arial,system-ui,sans-serif'};
Object.entries(CC_BRAND.colors).forEach(([k,v])=>document.documentElement.style.setProperty('--cc-'+k,v));
const CC_KEY='qh-betty-local-demo-v1';
function ccConfirm(message){return new Promise(resolve=>{const dialog=document.createElement('dialog');dialog.className='cc-confirm';dialog.innerHTML=`<h2>Review this change</h2><p>${esc(message)}</p><div class="cc-actions"><button class="primary" data-confirm>Confirm change</button><button class="secondary" data-cancel>Keep current settings</button></div>`;document.body.append(dialog);const finish=value=>{dialog.close();dialog.remove();resolve(value);};dialog.querySelector('[data-confirm]').onclick=()=>finish(true);dialog.querySelector('[data-cancel]').onclick=()=>finish(false);dialog.oncancel=e=>{e.preventDefault();finish(false);};dialog.showModal();});}
const ccDefaults=()=>({version:1,updated:null,editor:'Local demo',sources:{website:true,products:true,accounts:true,lit:false,news:false},policy:{competitor:'off',length:'default',tone:'Friendly',showSources:true,logging:false,market:'New York',avoid:'',disclaimer:'',escalation:''},dataset:null,previousDataset:null,content:[],events:[],audit:[]});
let ccStore;try{ccStore=JSON.parse(localStorage.getItem(CC_KEY))||ccDefaults();}catch{ccStore=ccDefaults();}
function ccPersist(next){const serialized=JSON.stringify(next);localStorage.setItem(CC_KEY,serialized);if(localStorage.getItem(CC_KEY)!==serialized)throw Error('Storage did not confirm this change.');ccStore=next;}
function ccCommit(change,label){const next=structuredClone(ccStore);change(next);next.audit.push({at:new Date().toISOString(),action:label});ccPersist(next);}
function ccEvent(type,sourceIds=[]){try{ccCommit(s=>s.events.push({type,sourceIds,at:new Date().toISOString(),version:s.version}),'Local '+type);}catch{}}
const CC_SOURCES=[['website','Betty’s Website','Available public brand reference'],['products','Product Information','Available public product reference'],['accounts','Account / Retailer Data','Synthetic sample records · Oct 6, 2026'],['lit','LIT Alerts','Needs setup · manual CSV import'],['news','Cannabis News Sources','Needs approval · saved references only']];
function ccEligible(id,state=ccStore){return !!state.sources[id]&&(id!=='lit'||!!state.dataset);}
function ccLogo(){return `<span class="cc-brand"><img src="${CC_BRAND.logo}" alt="Betty’s Eddies"><strong>QUICKHITS</strong><small>${CC_BRAND.tagline}</small></span>`;}
function ccSafeURL(value){try{const u=new URL(value);return u.protocol==='https:'&&!/^(localhost|127\.|10\.|192\.168\.|169\.254\.|172\.(1[6-9]|2\d|3[01])\.|\[|0\.)/i.test(u.hostname)&&u.hostname.includes('.')&&!u.username&&!u.password?u.href:null;}catch{return null;}}
function ccCSV(text){let rows=[],row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(field);field='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(field);if(row.some(x=>x.trim()))rows.push(row);row=[];field='';}else field+=c;}if(quoted)throw Error('Unclosed quoted field.');row.push(field);if(row.some(x=>x.trim()))rows.push(row);return rows;}
function ccValidateImport(rows,mapping,meta){if(!meta.period||!meta.territory)throw Error('Reporting period and territory are required.');if(rows.length<2)throw Error('No data rows.');const errors=[],seen=new Set(),records=[];rows.slice(1).forEach((row,i)=>{if(row.length!==rows[0].length){errors.push(`Row ${i+2}: column count mismatch.`);return;}const name=(row[mapping.name]||'').trim(),raw=row[mapping.value]||'',value=Number(raw.replace(/[$,%\s]/g,''));if(!name||!raw.trim()||!Number.isFinite(value)||value<0){errors.push(`Row ${i+2}: name and nonnegative numeric value required.`);return;}const key=JSON.stringify(row);if(seen.has(key))return;seen.add(key);const matches=ACCOUNTS.filter(a=>a.name.toLowerCase()===name.toLowerCase());records.push({name,value,account:matches.length===1?matches[0].id:null,match:matches.length===1?'Exact sample account':'Unmatched · market aggregate only',fields:Object.fromEntries(rows[0].map((h,j)=>[h,row[j]])),sourceId:'lit',file:meta.file,row:i+2,sheet:'CSV',period:meta.period,territory:meta.territory,ingestedAt:new Date().toISOString()});});return {records,errors,...meta};}
