'use strict';
// Final rep refinements reuse shared CRM, Ask, audio and email services.
CC_BRAND.logo='assets/cc-transparent-logo.png';
ccLogo=()=>`<span class="cc-brand"><span class="cc-logo-window"><img src="${CC_BRAND.logo}" alt="Betty’s Eddies" style="position:absolute;left:-5.071%;top:-87.021%;width:109.533%!important;max-width:none!important;height:auto!important;background:transparent!important;border-radius:0!important"></span></span>`;
const meetingTile=ccDestinations.findIndex(d=>d[0]==='meetings');if(meetingTile>=0)ccDestinations.splice(meetingTile,1);
ccDestinations.find(d=>d[0]==='followups')[1]='What Do I Owe?';
ccHome=()=>`<h1>What do you need<br><em>right now?</em></h1><div class="cc-home-grid">${ccDestinations.map(([route,label,glyph],i)=>`<a class="cc-tile cc-tile-${i}" href="#${route}">${ccGlyph(glyph)}<strong>${label}</strong></a>`).join('')}</div><div class="cc-dashboard-tools"><a href="#report">Field Reports</a><a href="#visits">Meeting Notes</a><a href="#more">More tools</a></div>`;
const ccSuggestedQuestions=["What's on my schedule today?","What's the best-selling product in New York?","Who are my competitors?","What's the news that matters today?"];
function ccSuggestedPrompts(){return '<section class="cc-suggested" aria-labelledby="cc-suggested-title"><h2 id="cc-suggested-title">Try asking</h2><ul class="cc-suggested-list">'+ccSuggestedQuestions.map(q=>'<li>'+esc(q)+'</li>').join('')+'</ul></section>';}
ccVoice=()=>`<section class="cc-voice ${ccReply?'cc-has-answer':''} ${ccAskOverlay?'':'cc-voice-home'}" data-state="${ccBusy?'thinking':'idle'}">${ccAskOverlay?'':`<a class="cc-voice-logo" href="#home" aria-label="Ask Betty home">${ccLogo()}</a>`}${ccAskOverlay?'<h1>TAP TO SPEAK</h1>':''}<button class="cc-mic" data-cc="mic" aria-label="Tap to speak">${icon('mic')}</button>${ccAskOverlay?'':'<h1>TAP TO SPEAK</h1>'}<p id="cc-voice-status" role="status"></p>${!ccAskOverlay&&!ccReply?ccSuggestedPrompts():''}<div class="cc-compose" ${ccAskOverlay?'':'hidden'}><form id="cc-question"><textarea aria-label="Ask your question here" placeholder="Ask your question here" id="cc-input" rows="3" maxlength="2000">${esc(ccTranscript)}</textarea><button class="primary" type="submit">Send</button></form></div>${ccReply?ccPanel('Your answer',`<p class="cc-answer">${esc(ccReply).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/https:\/\/[^\s<>]+/g,u=>'<a href="'+u.replace(/[).,]+$/,'')+'" target="_blank" rel="noopener">View source</a>')}</p><div class="cc-actions"><button class="secondary" data-cc="reply-listen">Listen again</button><button class="secondary" data-live-reply-email>Use in Email</button><button class="secondary" data-rev-reply-copy>Copy</button></div>`):''}${ccAskOverlay||ccReply?'<button class="secondary" data-cc-end>End session</button>':''}</section>`;
function revisionNav(){if(document.body.classList.contains('cc-admin'))return;document.querySelector('.topbar').innerHTML=`<a class="betty-header-lockup" href="#home" aria-label="Ask Betty home">${ccLogo()}</a><nav aria-label="QuickHits navigation"><button class="secondary" data-rev-back>Back</button><button class="secondary" data-global-ask aria-label="Ask Betty">${icon('mic')}<span>Ask Betty</span></button><a class="secondary" href="#home">QuickHits</a></nav>`;}
let revisionPanelFocus=null;
function revisionPanel(title,html){stopAudio();document.getElementById('cc-global-ask')?.close();document.getElementById('cc-detail-panel')?.remove();revisionPanelFocus=document.activeElement;const panel=document.createElement('dialog');panel.id='cc-detail-panel';panel.setAttribute('aria-label',title);panel.innerHTML=`<div class="cc-panel-head"><h2>${esc(title)}</h2><button class="secondary" data-rev-close>Close</button></div>${html}`;document.body.append(panel);panel.addEventListener('close',()=>{panel.remove();revisionPanelFocus?.focus?.();});panel.show();panel.querySelector('button').focus();}
const revisionPrint=text=>`<div class="cc-written">${esc(text).split('\n').map(l=>l?`<p>${l}</p>`:'').join('')}</div>`;
function revisionAccountText(id){const a=crmAccount(id);if(!a)return 'Account unavailable.';return [a.name,[a.address,a.city,a.region].filter(Boolean).join(', '),...crmContacts(id).map(c=>c.name+' · '+c.role),a.background||a.action,...crmUpdates(id).map(u=>'Update: '+u.summary),...crmNotes(id).map(n=>'Note ('+crmWhen(n.date)+'): '+n.text),...followupRows().filter(t=>t.account===id&&!t.done).map(t=>'You owe: '+t.action+' · '+crmWhen(t.due)),a.metric?`${ccCount(a.metric.est_units)} estimated units; ${ccMoney(a.metric.est_total_value)} estimated value. Reporting period: ${ccPeriod()}.`:''].filter(Boolean).join('\n\n');}
const revisionAccountBase=ccLiveAccountPage;ccLiveAccountPage=id=>{let html=revisionAccountBase(id);const a=crmAccount(id);if(!a)return html;const start=html.indexOf('<div class="cc-actions">'),end=html.indexOf('</div>',start);html=html.slice(0,start)+`<div class="cc-actions"><button class="primary" data-rev-account-listen="${esc(id)}">Listen</button><button class="secondary" data-rev-account-read="${esc(id)}">Read</button><a class="secondary" href="#notes/${encodeURIComponent(id)}">Log a Note</a><button class="secondary" data-live-email="${esc(id)}">Email Contact</button></div>`+html.slice(end+6);return html.replace('<h2>Follow Ups</h2>','<h2>What Do I Owe?</h2>');};
function revisionBriefText(){const meetings=crmBriefMeetings();if(ccLiveBriefTab==='meetings'){const m=meetings[ccCRMMeeting];if(!m)return 'No meetings scheduled.';const c=crmContacts(m.account_id).find(c=>c.id===m.contact_id)||crmContacts(m.account_id)[0];return [crmAccount(m.account_id)?.name,crmWhen(m.date),c?[c.name,c.role].filter(Boolean).join(' · '):'',m.address,crmAccount(m.account_id)?.address,m.objective,m.prep,...crmNotes(m.account_id).map(n=>'Last conversation: '+n.text),...followupRows().filter(t=>t.account===m.account_id&&!t.done).map(t=>'You owe: '+t.action+' · '+crmWhen(t.due))].filter(Boolean).join('\n\n');}if(ccLiveBriefTab==='updates')return crmUpdates().map(u=>crmAccount(u.account_id)?.name+'\n'+u.title+'\n'+u.summary).join('\n\n');if(ccLiveBriefTab==='followups')return followupRows().filter(t=>!t.done).map(t=>crmAccount(t.account)?.name+'\n'+t.action+'\nDue '+crmWhen(t.due)).join('\n\n');return revisionNews().map(n=>n.headline+'\n'+n.summary+'\n'+n.source_name+' · '+n.published_at.slice(0,10)).join('\n\n');}
ccLiveBrief=()=>{const meetings=crmBriefMeetings(),due=followupRows().filter(t=>!t.done&&t.due&&t.due.slice(0,10)<=followupToday());ccCRMMeeting=Math.max(0,Math.min(ccCRMMeeting,meetings.length-1));const m=meetings[ccCRMMeeting],c=m&&(crmContacts(m.account_id).find(c=>c.id===m.contact_id)||crmContacts(m.account_id)[0]);const content={meetings:m?`<h2>${crmLink(m.account_id)}</h2><p>${esc(crmWhen(m.date))}</p><p>${esc(c?[c.name,c.role].filter(Boolean).join(' · '):'')}</p><p>${esc([m.address,crmAccount(m.account_id)?.address].filter(Boolean).join(' · '))}</p><strong>${esc(m.objective)}</strong><p>${esc(m.prep)}</p>`:'<p>No meetings scheduled.</p>',updates:crmCards(crmUpdates(),u=>`<article><h3>${crmLink(u.account_id)}</h3><strong>${esc(u.title)}</strong><p>${esc(u.summary)}</p></article>`),followups:revisionOwedCards(due),news:ccLiveNews()};return `<h1>Daily Brief</h1><h2>Today at a Glance</h2><div class="cc-stats">${[['meetings','Meetings',meetings.length],['updates','Accounts With Updates',new Set(crmUpdates().map(u=>u.account_id)).size],['followups','What Do I Owe?',due.length],['news','News Items',revisionNews().length]].map(([k,label,count])=>`<button data-live-tab="${k}" aria-pressed="${ccLiveBriefTab===k}"><b>${count}</b>${label}</button>`).join('')}</div><section class="cc-panel cc-brief-card">${content[ccLiveBriefTab]}<div class="cc-brief-actions"><button class="primary" data-rev-brief-listen>Listen to Your Brief</button><button class="secondary" data-rev-brief-read>Read Your Brief</button><button class="secondary" data-rev-brief-email>Send an Email</button></div>${ccLiveBriefTab==='meetings'?`<div class="cc-brief-pager"><button class="secondary" data-crm-meeting="-1" ${ccCRMMeeting===0?'disabled':''}>Previous</button><span>${meetings.length?ccCRMMeeting+1:0} of ${meetings.length}</span><button class="secondary" data-crm-meeting="1" ${ccCRMMeeting>=meetings.length-1?'disabled':''}>Next</button></div>`:''}</section>`;};
function revisionAttention(id){const tasks=followupRows().filter(t=>t.account===id&&!t.done),today=followupToday();if(tasks.some(t=>t.due&&t.due.slice(0,10)<=today))return {label:'Needs Attention',reason:'An open commitment is due.',rank:0};if(tasks.some(t=>t.due))return {label:'Follow Up Soon',reason:'A dated follow-up is open.',rank:1};const a=crmAccount(id);if(/active/i.test(a?.status||''))return {label:'Active',reason:'Account status',rank:2};return null;}
ccLiveAccounts=()=>`<h1>My Accounts</h1><label>Find an account<input id="cc-live-search" type="search" value="${esc(accountQuery)}" placeholder="Search accounts"></label><div class="cc-account-grid">${crmCards(ACCOUNTS.filter(a=>[a.name,a.city,a.contact].join(' ').toLowerCase().includes(accountQuery.toLowerCase())).sort((a,b)=>(revisionAttention(a.id)?.rank??9)-(revisionAttention(b.id)?.rank??9)),a=>{const attention=revisionAttention(a.id);return `<a class="cc-panel cc-account-link" href="#account/${encodeURIComponent(a.id)}">${attention?`<span class="cc-tag cc-attention-${attention.rank}" title="${esc(attention.reason)}">${attention.label}</span>`:''}<h2>${esc(a.name)}</h2><p>${esc([a.city,a.region].filter(Boolean).join(', '))}</p><strong>${esc(a.contact)}</strong><p>${esc(a.action||'')}</p>${a.metric?`<small>${ccCount(a.metric.est_units)} estimated units · ${esc(ccPeriod())}</small>`:''}</a>`;},'No matching accounts.')}</div>`;
function revisionProspectPriority(p){if(/hot|urgent/i.test(p.status))return {label:'HOT',rank:0};if(/requested|request|waiting|interested/i.test(p.reason+' '+p.status))return {label:'REQUEST TO FULFILL',rank:1};if(/new/i.test(p.status))return {label:'NEW',rank:2};return {label:p.status||'Next conversation',rank:3};}
crmProspects=()=>'<h1>Prospects</h1><p>Start with the buyers who have asked for something.</p><div class="cc-account-grid">'+crmCards([...crmRows('prospects')].sort((a,b)=>revisionProspectPriority(a).rank-revisionProspectPriority(b).rank),p=>{const priority=revisionProspectPriority(p);return ccPanel(esc(p.name),`<span class="cc-tag">${esc(priority.label)}</span><p>${esc([p.city,p.state].filter(Boolean).join(', '))}</p><strong>${esc(p.contact)} · ${esc(p.role)}</strong><p>${esc(p.reason)}</p><h3>Next action</h3><p>${esc(p.next_action)}</p>${p.last_touch?`<small>Last touch ${esc(crmWhen(p.last_touch))}</small>`:''}<div class="cc-actions"><button class="primary" data-crm-prospect-email="${esc(p.id)}">Email Contact</button></div>`);})+'</div>';
function revisionOwedCards(tasks){return crmCards([...tasks].sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')),t=>{const why=crmNotes(t.account).slice(-1)[0]?.text||crmUpdates(t.account).slice(-1)[0]?.summary;return `<article class="cc-owe-item"><span class="cc-tag">${t.due&&t.due.slice(0,10)<followupToday()?'Past due':t.due?.slice(0,10)===followupToday()?'Due today':'Next commitment'}</span><h2>${crmLink(t.account)}</h2><h3>${esc(t.action)}</h3>${why?`<p><strong>Why it matters</strong><br>${esc(why)}</p>`:''}<p><strong>Due:</strong> ${esc(crmWhen(t.due)||'No date recorded')}${t.priority?' · '+esc(t.priority):''}</p><div class="cc-actions"><button class="primary" data-live-email="${esc(t.account)}" data-owed-id="${esc(t.id)}">Email Contact</button><a class="secondary" href="#notes/${encodeURIComponent(t.account)}">Log a Note</a>${crmLink(t.account,'View Account')}</div><details><summary>Update status</summary><button class="secondary" data-crm-task="${esc(t.id)}" data-status="completed">Mark completed</button></details></article>`;},'You have no open commitments.');}
ccTaskCards=id=>revisionOwedCards(followupRows().filter(t=>(!id||t.account===id)&&!t.done));
function revisionNews(){return [...(ccLive?.news||[])].filter(n=>ccSafeURL(n.source_url)).sort((a,b)=>new Date(b.published_at)-new Date(a.published_at)).slice(0,12);}
function revisionCategory(n){const text=[n.category,n.market,n.headline].join(' ');return /new york|\bNY\b/i.test(text)?'New York':/regulat|legal|law|policy/i.test(text)?'Regulation':/retail|dispensar/i.test(text)?'Retail':/brand|compet|launch/i.test(text)?'Brands / Competition':'Market / Industry';}
ccLiveNews=()=>revisionNews().map((n,i)=>`<article class="cc-news-item cc-panel"><span class="cc-tag">${revisionCategory(n)}</span><small>${esc(n.source_name)} · ${esc(n.published_at.slice(0,10))}</small><h2>${esc(n.headline)}</h2><p>${esc(n.summary)}</p><div class="cc-actions"><a class="secondary" href="${esc(ccSafeURL(n.source_url))}" target="_blank" rel="noopener">Read Article</a><button class="secondary" data-rev-news-listen="${i}">Listen</button></div></article>`).join('')||'<p>No current stories available.</p>';
ccLiveMarket=()=>{const categories=[...ccLive.categories].sort((a,b)=>b.est_units-a.est_units),top=categories[0],leaders=[...ccLive.dispensaries].sort((a,b)=>b.est_units-a.est_units).slice(0,3);return `<h1>Market Snaps / Trends</h1><div class="cc-account-grid">${ccPanel('Trends',`${top?`<h3>${esc(top.category)} leads reported unit movement</h3><p>${ccCount(top.est_units)} estimated units in this reporting period.</p>`:''}${leaders.map(r=>`<p><strong>${esc(r.dispensary)}</strong><br>${ccCount(r.est_units)} estimated units</p>`).join('')}${ccLiveSource()}`)}${ccPanel('What’s Moving',categories.map(r=>`<article><h3>${esc(r.category)}</h3><strong>${ccCount(r.est_units)} estimated units</strong><p>${ccMoney(r.est_total_value)} estimated value</p></article>`).join('')+ccLiveSource())}${ccPanel('In Your Market',`<p>${ccLive.dispensaries.length} dispensaries in the reporting period.</p><a href="#accounts">Explore accounts</a>`)}${ccPanel('Competitive Intel',revisionNews().filter(n=>/compet|brand/i.test(n.category+' '+n.headline)).slice(0,2).map(n=>`<h3>${esc(n.headline)}</h3><p>${esc(n.summary)}</p><a href="${esc(ccSafeURL(n.source_url))}" target="_blank" rel="noopener">Read source</a>`).join('')||'<p>No new competitive updates in the latest stories.</p>')}</div>`;};
const revisionAssetBase='https://www.bettyseddies.com/wp-content/uploads/2025/04/';
function revisionAssets(kind){return kind==='product'?officialCatalogItems().map(p=>({...p,title:p.name,url:revisionAssetBase+p.image,source:'https://www.bettyseddies.com/'})):[{title:'Betty’s Eddies logo',category:'Brand identity',url:new URL(CC_BRAND.logo,location.href).href,source:new URL(CC_BRAND.logo,location.href).href},...brandCreatives().filter(a=>a.id!=='brand-logo').map(a=>({...a,category:a.channel,source:'https://www.bettyseddies.com/'}))];}
function revisionAssetCards(kind){const assets=revisionAssets(kind),categories=[...new Set(assets.map(p=>p.category))];return categories.map(category=>`<section class="cc-asset-section"><h2>${esc(category)}</h2><div class="cc-asset-grid">${assets.map((a,index)=>({...a,index})).filter(a=>a.category===category).map(a=>`<article class="cc-panel cc-asset-card"><img src="${esc(a.url)}" alt="${esc(a.title)}" loading="lazy"><h3>${esc(a.title)}</h3>${a.description?`<p>${esc(a.description)}</p>`:''}${a.formats?`<small>${esc(a.formats)}</small>`:''}<a href="${esc(a.source)}" target="_blank" rel="noopener">${kind==='product'?'Product source':'View original source'}</a><div class="cc-actions"><button class="secondary" data-rev-asset="${kind}:${a.index}:copy">Copy</button><a class="secondary" href="${a.url.includes('/assets/')?esc(a.url):'/api/asset?name='+encodeURIComponent(a.url.split('/').pop())}" download>Download</a><button class="primary" data-rev-asset="${kind}:${a.index}:send">Send</button></div></article>`).join('')}</div></section>`).join('');}
ccCatalog=()=>'<h1>Products</h1><p>Explore the portfolio by category.</p>'+revisionAssetCards('product');
const revisionRenderBase=render;render=function(){revisionRenderBase();if(document.body.classList.contains('cc-admin'))return;revisionNav();const view=location.hash.slice(1).split('/')[0]||'session',main=document.getElementById('main');if(view==='catalog'||view==='products')main.innerHTML=ccCatalog();if(view==='brand')main.innerHTML='<h1>Brand</h1><p>Artwork and product graphics for your next retailer conversation.</p>'+revisionAssetCards('brand');if(view==='followups'&&ccLive){const add=main.querySelector('.followup-add')?.outerHTML||'';main.innerHTML='<h1>What Do I Owe?</h1><p>Your open promises, the context behind them, and the next step.</p>'+ccTaskCards()+add+(followupRows().some(t=>t.done)?'<details class="cc-panel"><summary>Completed commitments</summary>'+followupRows().filter(t=>t.done).map(t=>'<article><h3>'+esc(t.action)+'</h3>'+crmLink(t.account)+'<button class="secondary" data-crm-task="'+esc(t.id)+'" data-status="open">Reopen</button></article>').join('')+'</details>':'');crmPolish();}if(view==='meetings'){main.innerHTML='<h1>Meeting context</h1><a class="primary" href="#brief">Open Daily Brief</a>';}if(['session','ai'].includes(view))ccVoiceState(ccBusy?'thinking':ccRecognition?'listening':ccReply?'resolved':'idle');};
window.addEventListener('click',async e=>{const b=e.target.closest('[data-rev-reply-copy],[data-rev-back],[data-rev-close],[data-rev-brief-listen],[data-rev-brief-read],[data-rev-brief-email],[data-rev-account-read],[data-rev-account-listen],[data-rev-news-listen],[data-rev-asset],[data-owed-id]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();if(b.hasAttribute('data-rev-reply-copy')){try{await navigator.clipboard.writeText(ccReply);toast('Answer copied.');}catch{revisionPanel('Copy answer',`<textarea aria-label="Answer to copy" rows="8">${esc(ccReply)}</textarea>`);}return;}if(b.hasAttribute('data-rev-back')){if(history.length>1)history.back();else location.hash='session';}if(b.hasAttribute('data-rev-close'))document.getElementById('cc-detail-panel')?.close();if(b.hasAttribute('data-rev-brief-listen'))speak(revisionBriefText());if(b.hasAttribute('data-rev-brief-read'))revisionPanel('Your written brief',revisionPrint(revisionBriefText()));if(b.hasAttribute('data-rev-brief-email')){const m=crmBriefMeetings()[ccCRMMeeting];openEmailDraft({account:m?.account_id,text:revisionBriefText()});}if(b.dataset.revAccountRead)revisionPanel(crmAccount(b.dataset.revAccountRead)?.name||'Account',revisionPrint(revisionAccountText(b.dataset.revAccountRead)));if(b.dataset.revAccountListen)speak(revisionAccountText(b.dataset.revAccountListen));if(b.dataset.revNewsListen!==undefined){const n=revisionNews()[Number(b.dataset.revNewsListen)];if(n)speak(n.headline+'. '+n.summary);}if(b.dataset.owedId){const t=followupRows().find(t=>t.id===b.dataset.owedId);openEmailDraft({account:t.account,text:'Subject: '+t.action+'\n\nHello,\n\nFollowing up on '+t.action+'.\n\nBest,\nHarry'});}if(b.dataset.revAsset){const menu=b.closest('details');if(menu)menu.open=false;const [kind,index,action]=b.dataset.revAsset.split(':'),a=revisionAssets(kind)[Number(index)];if(!a)return;const text=[a.title,a.description,a.formats,'Image: '+a.url].filter(Boolean).join('\n');if(action==='copy'){try{await navigator.clipboard.writeText(text);toast('Copied.');}catch{revisionPanel('Copy information',`<textarea aria-label="Information to copy" rows="8">${esc(text)}</textarea>`);}}if(action==='send')openEmailDraft({account:ccAccount||undefined,text:'Subject: Betty’s Eddies — '+a.title+'\n\n'+text});}},true);
window.addEventListener('click',e=>{if(e.target.closest('[data-global-ask]')){document.getElementById('cc-detail-panel')?.close();document.getElementById('email-dialog')?.close();}},true);
window.addEventListener('hashchange',()=>document.getElementById('cc-detail-panel')?.close());
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.getElementById('cc-detail-panel')?.close();});
render();

const revisionEmailBase=openEmailDraft;openEmailDraft=function(message){document.getElementById('cc-detail-panel')?.close();document.getElementById('cc-global-ask')?.close();revisionEmailBase(message);const dialog=document.getElementById('email-dialog');if(dialog.matches(':modal')){dialog.close();dialog.show();}};

// Keep the single audio controller alive across answer renders and panel closes.
const ccMobileAudioBar=document.getElementById('persistent-audio');
const ccMobileRender=render;render=function(){if(ccMobileAudioBar)document.body.append(ccMobileAudioBar);ccMobileRender();const host=document.querySelector('.cc-voice')||document.querySelector('main');if(host&&ccMobileAudioBar)host.append(ccMobileAudioBar);};


// Voice and dashboard share one home page; overlay Ask remains compact.
const ccScrollDashboard=ccHome;
const ccScrollVoice=ccVoice;
function ccHomeTools(){
 return '<section id="cc-home-tools" class="cc-home-tools" aria-labelledby="cc-home-tools-title">'+ccScrollDashboard().replace('<h1>','<h2 id="cc-home-tools-title">').replace('</h1>','</h2>')+'</section>';
}
ccVoice=function(){
 const voice=ccScrollVoice();
 return ccAskOverlay?voice:voice.replace('class="cc-explore cc-quickhits-link"','data-cc-scroll-tools class="cc-explore cc-quickhits-link"')+ccHomeTools();
};
ccHome=()=>ccVoice();
const ccScrollRender=render;
render=function(){
 ccScrollRender();
 const view=location.hash.slice(1).split('/')[0]||'session';
 const home=['home','session','ai'].includes(view);
 document.body.classList.toggle('cc-unified-home',home);
 if(home){
  document.body.classList.add('cc-session');
  ccVoiceState(ccBusy?'thinking':ccRecognition?'listening':ccReply?'resolved':'idle');
 }
};
document.addEventListener('click',event=>{
 if(!event.target.closest('[data-cc-scroll-tools]'))return;
 const tools=document.getElementById('cc-home-tools');
 if(!tools)return;
 event.preventDefault();
 tools.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});
 const heading=tools.querySelector('h2');
 heading.setAttribute('tabindex','-1');
 heading.focus({preventScroll:true});
});
render();


