function crmBriefMeetings(){const today=ccLive?.current_local_date||new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(new Date());return crmRows('meetings').filter(m=>!/(cancel|completed)/i.test(m.status)&&String(m.date).slice(0,10)===today).sort((a,b)=>a.date.localeCompare(b.date));}
'use strict';
const ccSharedWrites=true;
let ccAskOverlay=false,ccLoadVersion=0,ccCRMMeeting=0;
function crmWhen(value){if(!value)return '';const dateOnly=/^\d{4}-\d{2}-\d{2}$/.test(value);const d=new Date(dateOnly?value+'T12:00:00Z':value);if(dateOnly)return d.toLocaleDateString('en-US',{timeZone:'America/New_York',month:'short',day:'numeric'});return Number.isNaN(d.getTime())?value:d.toLocaleString('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});}
const crmRows=table=>ccLive?.crm?.[table]||[];
const crmAccount=id=>ACCOUNTS.find(a=>a.id===id);
const crmLink=(id,label)=>id?`<a href="#account/${encodeURIComponent(id)}">${esc(label||crmAccount(id)?.name||'View account')}</a>`:'';
const crmCards=(rows,fn,empty='Nothing here yet.')=>rows.length?rows.map(fn).join(''):`<p>${empty}</p>`;
const crmContacts=id=>crmRows('contacts_demo').filter(r=>r.account_id===id);
const crmNotes=id=>[...crmRows('meeting_notes'),...(!ccSharedWrites?notes.filter(n=>n.local).map(n=>({...n,account_id:n.account})):[])].filter(r=>!id||r.account_id===id);
const crmUpdates=id=>crmRows('account_updates').filter(r=>!id||r.account_id===id);
function ccApplyCRM(){if(!ccLive)return;const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');const source=crmRows('accounts');const list=source.map(r=>{const c=crmContacts(r.id)[0]||{},metric=ccLive.dispensaries.find(d=>norm(d.dispensary)===norm(r.analytics_name||r.name));return {...r,name:r.name||'Account',contact:c.name||'',role:c.role||'',email:c.email||'',region:r.state||'',skus:[],previous:[],opportunity:r.background||'',action:r.next_action||'',last:'',metric};});for(const d of ccLive.dispensaries){if(!list.some(a=>a.metric?.id===d.id))list.push({id:'lit-'+d.id,name:d.dispensary,city:'',region:d.market||'',contact:'',role:'',email:'',skus:[],previous:[],action:'',metric:d});}ACCOUNTS.splice(0,ACCOUNTS.length,...list);STOPS.splice(0,STOPS.length,...crmRows('meetings').map(r=>({id:r.account_id,time:r.time||r.date,focus:r.objective})));}
ccLoadLive=async function(){const version=++ccLoadVersion;ccLoadError='';try{const response=await fetch('/api/data?exclude='+encodeURIComponent(ccDisabledSources().join(',')));if(!response.ok)throw Error();const next=await response.json();if(version!==ccLoadVersion)return;if(!Array.isArray(next.dispensaries)||!next.crm)throw Error();for(const key of Object.keys(next.crm)){if(next.crm[key]===null&&ccLive?.crm?.[key])next.crm[key]=ccLive.crm[key];}ccLive=next;ccApplyCRM();}catch{if(version!==ccLoadVersion)return;ccLoadError='Your updates are temporarily unavailable. Try again.';}render();};
followupRows=function(){const shared=crmRows('follow_ups').map(r=>({...r,account:r.account_id,done:/done|complete/i.test(r.status),waiting:/waiting/i.test(r.status),source:'Follow Up'}));return ccSharedWrites?shared:[...shared,...manualFollowups.map(t=>({...t,done:!!followupDone[t.id]}))];};
ccLiveAccount=id=>{const a=crmAccount(id);return a?{...a.metric,dispensary:a.name,id:a.id}:null;};
ccLiveAccounts=function(){const rows=ACCOUNTS.filter(a=>a.name.toLowerCase().includes(accountQuery.toLowerCase()));return '<h1>My Accounts</h1><label>Find an account<input id="cc-live-search" type="search" value="'+esc(accountQuery)+'" placeholder="Search accounts"></label><div class="cc-account-grid">'+crmCards(rows,a=>`<a class="cc-panel cc-account-link" href="#account/${encodeURIComponent(a.id)}"><h2>${esc(a.name)}</h2><p>${esc([a.city,a.region].filter(Boolean).join(', '))}</p><strong>${esc(a.contact)}</strong><p>${esc(a.action||a.status||'')}</p>${a.metric?`<small>${ccCount(a.metric.est_units)} estimated units · ${esc(ccPeriod())}</small>`:''}</a>`,'No matching accounts.')+'</div>';};
function crmMeetingCard(m){const c=crmRows('contacts_demo').find(c=>c.id===m.contact_id)||crmContacts(m.account_id)[0];return `<article><h3>${crmLink(m.account_id)}</h3><p>${esc([crmWhen(m.date),m.time].filter(Boolean).join(' · '))}</p>${c?`<p>${esc(c.name)}${c.role?' · '+esc(c.role):''}</p>`:''}<p>${esc([m.address,crmAccount(m.account_id)?.address].filter(Boolean).join(' · '))}</p><strong>${esc(m.objective)}</strong><p>${esc(m.prep)}</p><div class="cc-actions"><button class="secondary" data-live-ask="Prepare me for my meeting with ${esc(crmAccount(m.account_id)?.name||'this account')}">Read the Brief</button><button class="secondary" data-live-email="${esc(m.account_id)}">Send Email</button></div></article>`;}
function crmMeetingPanel(){const meetings=crmBriefMeetings();if(!meetings.length)return '<p>No meetings scheduled.</p>';ccCRMMeeting=Math.min(ccCRMMeeting,meetings.length-1);return crmMeetingCard(meetings[ccCRMMeeting])+`<div class="cc-actions"><button class="secondary" data-crm-meeting="-1" ${ccCRMMeeting===0?'disabled':''}>Previous</button><span>${ccCRMMeeting+1} of ${meetings.length}</span><button class="secondary" data-crm-meeting="1" ${ccCRMMeeting===meetings.length-1?'disabled':''}>Next</button></div>`;}
ccTaskCards=function(id){return crmCards(followupRows().filter(t=>!id||t.account===id),t=>`<article class="cc-task"><h3>${esc(t.action)}</h3>${crmLink(t.account)}<p>${esc(crmWhen(t.due)||'No due date')} · ${esc(t.status||'Open')}${t.priority?' · '+esc(t.priority):''}</p><div class="cc-actions"><button class="secondary" ${ccSharedWrites?`data-crm-task="${esc(t.id)}" data-status="${t.done?'open':'completed'}"`:`data-followup-toggle="${esc(t.id)}"`}>${t.done?'Reopen':'Mark done'}</button><button class="secondary" data-live-email="${esc(t.account)}">Send Email</button></div></article>`,'No follow-ups added yet.');};
ccLiveBrief=function(){const due=followupRows().filter(t=>!t.done&&t.due&&t.due.slice(0,10)<=followupToday());const updates=crmUpdates();const panels={meetings:crmMeetingPanel(),updates:crmCards(updates,u=>`<article><h3>${crmLink(u.account_id)}</h3><strong>${esc(u.title)}</strong><p>${esc(u.summary)}</p><small>${esc(crmWhen(u.date))}</small></article>`,'No account updates.'),followups:crmCards(due,t=>`<article><h3>${esc(t.action)}</h3>${crmLink(t.account)}<p>${esc(crmWhen(t.due))} · ${esc(t.priority)}</p></article>`,'No follow-ups due.'),news:ccLiveNews()};return `<h1>Daily Brief</h1><h2>Today at a Glance</h2><div class="cc-stats">${[['meetings','Meetings',crmBriefMeetings().length],['updates','Accounts With Updates',new Set(updates.map(u=>u.account_id)).size],['followups','Follow Ups Due',due.length],['news','News Items',ccLive.news.length]].map(([key,label,n])=>`<button data-live-tab="${key}" aria-pressed="${ccLiveBriefTab===key}"><b>${n}</b>${label}</button>`).join('')}</div>${ccPanel('Your briefing',panels[ccLiveBriefTab])}<div class="cc-actions"><button class="primary" data-crm-brief-listen>Listen to Your Brief</button>${ccLiveBriefTab==='meetings'?'':'<button class="secondary" data-live-ask="Give me my daily brief from meetings, account updates and follow ups.">Read the Brief</button><button class="secondary" data-crm-brief-email>Send Email</button>'}</div>${ccPanel('Latest sales picture',`<strong>${ccCount(ccLive.totals.estimated_units)} estimated units</strong><p>${ccMoney(ccLive.totals.estimated_value)} estimated value</p>${ccLiveSource()}`)}`;};
ccLiveAccountPage=function(id){const a=crmAccount(id);if(!a)return ccPanel('Account unavailable','<a href="#accounts">View accounts</a>');ccAccount=id;selectedAccount=id;const contacts=crmContacts(id),meetings=crmRows('meetings').filter(m=>m.account_id===id),saved=crmNotes(id);return `<a href="#accounts">Accounts</a><h1>${esc(a.name)}</h1><p>${esc([a.address,a.city,a.region].filter(Boolean).join(', '))}</p><div class="cc-actions"><button class="primary" data-live-ask="Tell me about ${esc(a.name)}">Read</button><button class="secondary" data-live-listen-account="${esc(id)}">Listen</button><a class="secondary" href="#notes/${encodeURIComponent(id)}">Log Note</a><button class="secondary" data-live-email="${esc(id)}">Email Contact</button></div>${ccPanel('Overview',`<p>${esc(a.background||a.opportunity||'')}</p>`+crmCards(contacts,c=>`<p><strong>${esc(c.name)}</strong> · ${esc(c.role)}</p>${c.email?`<p>${esc(c.email)}</p>`:''}`,'No contact details added.'))}${a.metric?ccPanel('Sales movement',`<strong>${ccCount(a.metric.est_units)} estimated units</strong><p>${ccMoney(a.metric.est_total_value)} estimated value</p>${ccLiveSource()}`):''}${ccPanel('Meeting Prep',crmCards(meetings,crmMeetingCard,'No meetings scheduled.'))}${ccPanel('What Changed',crmCards(crmUpdates(id),u=>`<article><strong>${esc(u.title)}</strong><p>${esc(u.summary)}</p><small>${esc(crmWhen(u.date))}</small></article>`,'No account updates.'))}${ccPanel('Recent Notes',crmCards(saved,n=>`<article><small>${esc(crmWhen(n.date))}</small><p>${esc(n.text)}</p><button class="secondary" data-crm-note-email="${esc(n.id)}">Send as Email</button></article>`,'No saved notes yet.'))}${ccPanel('Products','<a href="#catalog">View the product portfolio</a>')}${ccPanel('Competition','<p>No account-specific competitive figures are available.</p>')}${ccPanel('Follow Ups',ccTaskCards(id))}${ccPanel('Past Conversations',crmCards(saved,n=>`<p>${esc(crmWhen(n.date))} · ${esc(n.text)}</p>`,'No earlier conversations recorded.'))}`;};
function crmProspects(){return '<h1>Prospects</h1><div class="cc-account-grid">'+crmCards(crmRows('prospects'),p=>ccPanel(esc(p.name),`<p>${esc([p.city,p.state].filter(Boolean).join(', '))}</p><strong>${esc(p.contact)} ${esc(p.role)}</strong><p>${esc(p.reason)}</p><p>${esc(p.next_action)}</p><small>${esc(p.status)}${p.last_touch?' · Last touch '+esc(p.last_touch):''}</small>${crmLink(p.account_id)}<div class="cc-actions"><button class="secondary" data-crm-prospect-email="${esc(p.id)}">Send Email</button></div>`),'No prospects available.')+'</div>';}
const crmPriorReport=reportPage;reportPage=function(){return '<h1>Field Reports</h1>'+crmCards(crmRows('field_reports'),r=>ccPanel(esc(crmWhen(r.date)),crmLink(r.account_id)+`<p>${esc(r.summary)}</p>${r.competitor?`<p>Competitor observed: ${esc(r.competitor)}</p>`:''}<p>${esc(r.feedback)}</p><p>${esc(r.issue)}</p><p>${esc(r.follow_up)}</p>`),'No field reports have been added.')+crmPriorReport().replace('<h1>Field Report</h1>','<h2>Your report</h2>');};
const crmVoiceMarkup=()=>`<section class="cc-voice" data-state="${ccBusy?'thinking':'idle'}">${ccAskOverlay?'':ccLogo()+`<a class="cc-explore" href="#home">CHECK OUT YOUR QUICK HITS</a>`}<button class="cc-mic" data-cc="mic" aria-label="Tap to speak">${icon('mic')}</button><h1>TAP TO SPEAK</h1><p id="cc-voice-status" role="status"></p><div class="cc-compose"><form id="cc-question"><label for="cc-input">ASK YOUR QUESTION HERE</label><textarea id="cc-input" rows="3" maxlength="2000">${esc(ccTranscript)}</textarea><button class="primary" type="submit">Send</button></form></div><button class="secondary" data-cc-end>End session</button>${ccReply?ccPanel('QuickHits',`<p class="cc-answer">${esc(ccReply).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/https:\/\/[^\s<>]+/g,u=>'<a href="'+u.replace(/[).,]+$/,'')+'" target="_blank" rel="noopener">View source</a>')}</p>${ccButton('Listen','reply-listen')}<button class="secondary" data-live-reply-email>Use in Email</button>${ccAccount?`<a class="secondary" href="#account/${encodeURIComponent(ccAccount)}">View account</a>`:''}`):''}</section>`;
ccVoice=crmVoiceMarkup;
function ccStopAskPlayback(){window.ccPlayNextReply=false;ccAskRevision++;ccAskController?.abort();ccAskController=null;ccBusy=false;ccRecognition?.abort();ccRecognition=null;stopAudio();}
function crmGlobalAsk(question){ccAskOverlay=true;let dialog=document.getElementById('cc-global-ask');if(!dialog){dialog=document.createElement('dialog');dialog.id='cc-global-ask';dialog.setAttribute('aria-label','Ask QuickHits');dialog.addEventListener('close',()=>{ccStopAskPlayback();ccAskOverlay=false;const bar=document.getElementById('persistent-audio');if(bar&&dialog.contains(bar))document.body.append(bar);dialog.remove();});document.body.append(dialog);}if(question)ccTranscript=question;dialog.innerHTML='<button class="secondary cc-close-ask" data-close-ask aria-label="Close Ask and return to page">Close</button>'+ccVoice();if(!dialog.open)dialog.show();ccVoiceState(ccBusy?'thinking':ccRecognition?'listening':ccReply?'resolved':'idle');if(question)document.getElementById('cc-question')?.requestSubmit();}
const crmRenderPrior=render;render=function(){ccApplyCRM();const view=location.hash.slice(1).split('/')[0]||'session';if(ccAskOverlay){const dialog=document.getElementById('cc-global-ask');if(dialog?.open){dialog.innerHTML='<button class="secondary cc-close-ask" data-close-ask aria-label="Close Ask and return to page">Close</button>'+ccVoice();ccVoiceState(ccBusy?'thinking':ccReply?'resolved':'idle');return;}}crmRenderPrior();document.title='Betty’s Eddies QuickHits';if(view==='admin')return;if(!ccLive&&!['session','home','more'].includes(view)){document.getElementById('main').innerHTML=ccPanel(ccLoadError?'Unable to load your updates':'Checking your sources…',ccLoadError?'<button class="primary" data-live-retry>Try again</button>':'');return;}const main=document.getElementById('main');if(ccLive){if(view==='prospects')main.innerHTML=crmProspects();if(view==='meetings')main.innerHTML='<h1>Meeting Prep</h1>'+crmMeetingPanel();if(view==='followups')main.innerHTML='<h1>Follow Up</h1>'+ccTaskCards()+followupsPage().split('<details class="panel followup-add">').slice(1).map(s=>'<details class="panel followup-add">'+s).join('');if(view==='visits')main.innerHTML='<h1>Meeting Notes</h1>'+crmCards(crmNotes(),n=>ccPanel(esc(crmAccount(n.account_id)?.name||'Meeting note'),`<p>${esc(n.text)}</p>${crmLink(n.account_id)}`));}if(ccLoadError&&ccLive&&view!=='session'){const notice=document.createElement('p');notice.setAttribute('role','status');notice.textContent='Your saved view is still here. Updates will be available shortly.';main.prepend(notice);}const global=document.querySelector('.topbar a[aria-label="Ask QuickHits"]');if(global){global.removeAttribute('href');global.setAttribute('role','button');global.setAttribute('tabindex','0');global.setAttribute('data-global-ask','');global.innerHTML=icon('mic');}crmPolish();};
function crmPolish(){if(document.body.classList.contains('cc-admin'))return;document.querySelectorAll('[data-dictate],[data-cc="note-mic"]').forEach(b=>{if(b.getAttribute('aria-pressed')==='true')return;b.setAttribute('aria-label','Dictate into this field');b.title='Dictate into this field';b.innerHTML=icon('mic');b.classList.add('cc-field-mic');});for(const id of ['report-draft','email-body']){const input=document.getElementById(id);if(input&&!document.querySelector(`[data-dictate="${id}"]`))input.insertAdjacentHTML('afterend',`<button class="secondary cc-field-mic" type="button" data-dictate="${id}" aria-label="Dictate into this field" title="Dictate into this field">${icon('mic')}</button>`);}const action=document.querySelector('#followup-form input[name="action"]');if(action){action.id='cc-task-action';if(!document.querySelector('[data-dictate="cc-task-action"]'))action.insertAdjacentHTML('afterend',`<button class="secondary cc-field-mic" type="button" data-dictate="cc-task-action" aria-label="Dictate follow up">${icon('mic')}</button>`);}document.querySelectorAll('.demo-banner,footer').forEach(el=>el.hidden=true);}
const crmEmailPrior=openEmailDraft;openEmailDraft=function(m){crmEmailPrior(m);const a=crmAccount(m.account||ccAccount);if(a?.email)document.getElementById('email-to').value=a.email;crmPolish();};
function crmBriefText(){return crmRows('meetings').map(m=>[crmAccount(m.account_id)?.name,m.time||m.date,m.objective,m.prep].filter(Boolean).join('. ')).join('\n')+'\n'+crmUpdates().map(u=>u.summary).join('\n')+'\n'+followupRows().filter(t=>!t.done).map(t=>t.action+' — '+t.due).join('\n');}
document.addEventListener('click',e=>{const b=e.target.closest('[data-global-ask],[data-close-ask],[data-crm-meeting],[data-live-ask],[data-crm-brief-listen],[data-crm-brief-email],[data-crm-prospect-email],[data-crm-note-email]');if(!b)return;if(b.hasAttribute('data-global-ask')){e.preventDefault();e.stopImmediatePropagation();crmGlobalAsk();ccStartDictation('cc-input');}if(b.hasAttribute('data-close-ask')){ccStopAskPlayback();ccAskOverlay=false;document.getElementById('cc-global-ask').close();}if(b.hasAttribute('data-live-ask')){e.preventDefault();e.stopImmediatePropagation();crmGlobalAsk(b.dataset.liveAsk);}if(b.dataset.crmMeeting){ccCRMMeeting+=Number(b.dataset.crmMeeting);render();}if(b.hasAttribute('data-crm-brief-listen'))speak(crmBriefText());if(b.hasAttribute('data-crm-brief-email'))openEmailDraft({account:ccAccount,text:crmBriefText()});if(b.dataset.crmProspectEmail){const p=crmRows('prospects').find(p=>p.id===b.dataset.crmProspectEmail);openEmailDraft({account:p.account_id,text:'Subject: Checking in\n\nHello '+p.contact+',\n\n'+p.next_action+'\n\nRegards,\nHarry'});document.getElementById('email-to').value=p.email;}if(b.dataset.crmNoteEmail){const n=crmRows('meeting_notes').find(n=>n.id===b.dataset.crmNoteEmail);openEmailDraft({account:n.account_id,text:n.text});}},true);
document.addEventListener('keydown',e=>{if(e.target.matches('[data-global-ask]')&&['Enter',' '].includes(e.key)){e.preventDefault();crmGlobalAsk();ccStartDictation('cc-input');}});
render();document.body.classList.add('cc-ready');ccLoadLive();
let crmSaving=false;
const crmRequests=new Map();
async function crmSave(table,row,id){
 if(crmSaving)return false;
 const key=JSON.stringify({table,row:{...row,date:undefined},id});
 if(!crmRequests.has(key))crmRequests.set(key,crypto.randomUUID());
 crmSaving=true;
 const controls=[...document.querySelectorAll('[data-cc="note-save"],[data-crm-task],[data-crm-report-save],#followup-form button[type="submit"]')];
 controls.forEach(b=>{b.disabled=true;b.setAttribute('aria-busy','true');});
 try{
  const response=await fetch('/api/save-record',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({table,row,id,requestId:crmRequests.get(key)})});
  const result=await response.json();if(!response.ok)throw Error(result.error);
  await ccLoadLive();toast('Saved.');return true;
 }catch(error){toast(error.message||'Unable to save. Your draft is preserved.');return false;}
 finally{crmSaving=false;controls.forEach(b=>{b.disabled=false;b.removeAttribute('aria-busy');});}
}
window.addEventListener('click',async e=>{const b=e.target.closest('[data-cc="note-save"],[data-crm-task],[data-live-listen-account],[data-crm-report-save]');if(!b)return;if(!ccSharedWrites&&!b.hasAttribute('data-live-listen-account'))return;e.preventDefault();e.stopImmediatePropagation();if(b.dataset.cc==='note-save'){if(!ccNoteReview||!ccNoteDraft.trim())return;const text=ccNoteDraft,account=ccAccount;if(await crmSave('meeting_notes',{account_id:account,text,date:new Date().toISOString(),author:'Harry'})){ccNoteDraft='';ccNoteReview=false;location.hash='account/'+encodeURIComponent(account);render();}}if(b.dataset.crmTask)await crmSave('follow_ups',{status:b.dataset.status},b.dataset.crmTask);if(b.hasAttribute('data-live-listen-account')){const a=crmAccount(b.dataset.liveListenAccount);if(a){window.ccPlayNextReply=true;crmGlobalAsk('Tell me about '+a.name);}}if(b.hasAttribute('data-crm-report-save')){const text=document.getElementById('report-draft').value,account=document.getElementById('crm-report-account').value;await crmSave('field_reports',{account_id:account,summary:text,date:new Date().toISOString()});}},true);
window.addEventListener('submit',async e=>{if(e.target.id!=='followup-form'||!ccSharedWrites)return;e.preventDefault();e.stopImmediatePropagation();const f=new FormData(e.target),draft=Object.fromEntries(f);await crmSave('follow_ups',{account_id:draft.account,action:draft.action,owner:draft.owner,due:draft.due,status:draft.state==='waiting'?'waiting':'open'});},true);
const crmReportBase=reportPage;reportPage=function(){if(!ccSharedWrites)return crmReportBase();return crmReportBase()+`<label>Account for report<select id="crm-report-account"><option value="">Choose an account</option>${crmRows('accounts').map(a=>`<option value="${esc(a.id)}">${esc(a.name)}</option>`).join('')}</select></label><button class="primary" data-crm-report-save>Save Field Report</button>`;};

window.addEventListener("hashchange",()=>{const dialog=document.getElementById("cc-global-ask");if(dialog?.open){ccAskOverlay=false;dialog.close();render();}});
about=function(){return '<h1>Help & Support</h1>'+ccPanel('Just ask','<p>Tap the microphone or type a question. Ask about an account, prepare for a meeting, review market updates or draft your next email.</p>')+ccPanel('Keep the conversation moving','<p>Review and edit notes before saving. Email actions open a draft in Gmail for you to send.</p>');};
activity=function(){return '<h1>Activity</h1>'+crmCards(crmNotes(),n=>ccPanel(esc(crmAccount(n.account_id)?.name||'Meeting note'),`<small>${esc(crmWhen(n.date))}</small><p>${esc(n.text)}</p>${crmLink(n.account_id)}`),'No activity recorded.');};
const crmFormPolish=crmPolish;crmPolish=function(){crmFormPolish();if(document.body.classList.contains('cc-admin'))return;for(const el of document.querySelectorAll('#note-voice-status,#email-voice-status'))if(/browser|openai|implementation/i.test(el.textContent))el.textContent='';document.querySelectorAll('[data-cancel-dictation]').forEach(b=>{b.textContent='Stop';});};
function crmNormalizeVoice(){if(document.body.classList.contains('cc-admin'))return;for(const b of document.querySelectorAll('[data-dictate],[data-cc="note-mic"]')){if(b.getAttribute('aria-pressed')==='true')continue;if(!b.querySelector('svg'))b.innerHTML=icon('mic');b.classList.add('cc-field-mic');b.setAttribute('aria-label','Dictate into this field');b.title='Dictate into this field';}for(const p of document.querySelectorAll('main p.fineprint,dialog p.fineprint'))if(/demo|synthetic|browser speech|voice uses|implementation|No CRM connection/i.test(p.textContent))p.textContent='';}
const crmCopyObserver=new MutationObserver(()=>{crmCopyObserver.disconnect();crmNormalizeVoice();crmCopyObserver.observe(document.body,{childList:true,subtree:true});});crmCopyObserver.observe(document.body,{childList:true,subtree:true});
function crmMatchAccount(question){const normalize=s=>String(s).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim(),q=' '+normalize(question)+' ';const matches=ACCOUNTS.filter(a=>{const full=normalize(a.name),short=normalize(a.name.replace(/\b(dispensary|cannabis|wellness|company|co)\b/gi,''));return q.includes(' '+full+' ')||(short&&q.includes(' '+short+' '));});return matches.length===1?matches[0].id:null;}

const crmSavePolish=crmPolish;crmPolish=function(){crmSavePolish();for(const selector of ['#cc-note-account','#followup-form select[name="account"]']){const select=document.querySelector(selector);if(!select)continue;const selected=select.value;const allowed=crmRows('accounts');select.innerHTML='<option value="">Choose an account</option>'+allowed.map(a=>'<option value="'+esc(a.id)+'">'+esc(a.name)+'</option>').join('');select.value=allowed.some(a=>a.id===selected)?selected:'';if(selector==='#cc-note-account')ccAccount=select.value;} };

// Keep older device drafts available for review without merging them into shared records.
const crmNotesEditor=ccNotes;ccNotes=function(id){return crmNotesEditor(id)+(notes.some(n=>n.local)?'<details class="cc-panel"><summary>Earlier note drafts</summary>'+notes.filter(n=>n.local).map(n=>'<article><p>'+esc(n.text)+'</p><button class="secondary" data-recover-note="'+esc(n.id)+'">Review this draft</button></article>').join('')+'</details>':'');};
window.addEventListener('click',e=>{const b=e.target.closest('[data-recover-note]');if(!b)return;const note=notes.find(n=>n.local&&String(n.id)===b.dataset.recoverNote);if(note){ccNoteDraft=note.text;ccNoteReview=false;render();}},true);

const crmDraftPolish=crmPolish;crmPolish=function(){crmDraftPolish();if(location.hash==='#followups'&&manualFollowups.length&&!document.getElementById('crm-earlier-tasks')){document.getElementById('main').insertAdjacentHTML('beforeend','<details id="crm-earlier-tasks" class="cc-panel"><summary>Earlier follow-up drafts</summary>'+manualFollowups.map(t=>'<article><p>'+esc(t.action)+'</p><button class="secondary" data-recover-task="'+esc(t.id)+'">Review this draft</button></article>').join('')+'</details>');}};
window.addEventListener('click',e=>{const b=e.target.closest('[data-recover-task]');if(!b)return;const task=manualFollowups.find(t=>String(t.id)===b.dataset.recoverTask),form=document.getElementById('followup-form');if(task&&form){form.closest('details').open=true;form.elements.action.value=task.action;form.elements.owner.value=task.owner||'Harry';if(task.due)form.elements.due.value=task.due.slice(0,10);form.elements.account.value=crmRows('accounts').some(a=>a.id===task.account)?task.account:'';form.scrollIntoView({block:'center'});}},true);

reportText=function(){return 'QUICKHITS — FIELD REPORT\n\nSAVED NOTES\n'+(crmRows('meeting_notes').map(n=>(crmAccount(n.account_id)?.name||'Account')+' | '+crmWhen(n.date)+'\n'+n.text).join('\n\n')||'No meeting notes have been added.')+'\n\nOPEN FOLLOW-UPS\n'+followupRows().filter(t=>!t.done).map(t=>(crmAccount(t.account)?.name||'Account')+' | '+t.action+' | '+crmWhen(t.due)).join('\n');};
