'use strict';
// Reviewed public-source snapshot. Publication dates must never become refresh dates.
const NEWS_EDITION='2026-10-06';
const MARKET_NEWS=[
 {id:'ny-payment-watch',tag:'Buyer operations',title:'Payment reporting is a timely buyer-conversation topic',source:'Vicente LLP',kind:'Industry legal analysis',published:'2026-09-16',url:'https://vicentellp.com/insights/new-york-cab-meeting-cod-reporting-metrc-transfers-nursery-licenses/',regions:['Statewide'],summary:'Vicente’s recap of the September 10 advisory board meeting reports that cash-on-delivery reporting and invoice tracking moved into Metrc.',takeaway:'Have your finance or compliance team confirm account terms before an order discussion. This news does not indicate that any demo account has overdue payments.',scope:'Meeting recap, not an account credit check. OCM’s public guidance is linked for the underlying reporting process.',extra:{label:'OCM payment reporting guidance',url:'https://cannabis.ny.gov/delinquent-payment-reporting'}},
 {id:'ny-market-dashboard',tag:'Market access',title:'OCM adds a regional market-data resource',source:'New York OCM',kind:'Official release',published:'2026-09-03',url:'https://cannabis.ny.gov/9.3.26-ccb-release',regions:['Statewide'],summary:'OCM announced a Metrc-based market dashboard covering statewide and regional sales, category growth, transaction values and licensing, alongside 19 adult-use license approvals.',takeaway:'Use regional context to prepare territory reviews, and verify whether a newly licensed business is actually open before adding it to a prospect route.',scope:'The release describes market-level data. It does not supply sales for the demo accounts or establish a new customer relationship.'},
 {id:'rochester-enforcement',tag:'Local market context',title:'Rochester-area enforcement remains useful background',source:'New York OCM',kind:'Official release · background',published:'2026-08-03',url:'https://cannabis.ny.gov/greece-enforcement-action-release',regions:['Finger Lakes','Central NY'],background:true,summary:'OCM reported an enforcement operation in Greece involving illicit products and equipment; the agency said products were intended for Central New York distribution.',takeaway:'Keep legitimate supply-chain documentation ready for buyer questions. There is no verified connection to any demo customer and no assumed sales uplift.',scope:'Older regional background, not breaking news or an event from today.'}
];
let newsTerritory='All New York',includeBackground=false;
const displayNewsDate=d=>new Date(d+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
function editionNotice(){const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());return today===NEWS_EDITION?'Reviewed Oct 6, 2026 · Curated snapshot · Automatic daily refresh not configured':'Saved edition: Oct 6, 2026 · Not refreshed today · Check source pages for newer information';}
function territoryStories(territory,background=false){return MARKET_NEWS.filter(n=>(!n.background||background)&&(territory==='All New York'||n.regions.includes('Statewide')||n.regions.includes(territory)));}
function visibleStories(){return territoryStories(newsTerritory,includeBackground).filter(n=>newsFilter==='All topics'||n.tag===newsFilter);}
function newsCard(n,large=false){return `<article class="news-card sourced-card">${badge(n.tag,'blue')}<p class="source-meta">${esc(n.source)} · ${displayNewsDate(n.published)}</p><h3>${esc(n.title)}</h3><p>${esc(n.summary)}</p>${large?`<div class="rep-takeaway"><strong>For your next visit</strong><p>${esc(n.takeaway)}</p><small>QuickHits interpretation</small></div>`:''}<p class="fineprint">${esc(n.regions.join(' / '))} · ${esc(n.kind)}</p><div class="news-links"><a href="#news/${n.id}">View briefing →</a><a href="${n.url}" target="_blank" rel="noopener">Read source ↗</a></div></article>`;}
function dailyNewsText(territory){const rows=territoryStories(territory).slice(0,3);return `New York territory briefing. Reviewed September 25, 2026; this is a saved snapshot, not a live feed.\n\n${rows.map(n=>`${n.source}, ${displayNewsDate(n.published)}. ${n.summary}\nRep takeaway, our interpretation: ${n.takeaway}`).join('\n\n')}\n\nThese are statewide developments relevant to ${territory==='All New York'?'your New York territory':territory}. They do not establish changes at a specific customer. Source links are available in Market news. No automatic daily refresh is configured.`;}
function news(){const rows=visibleStories();return `${heading('DAILY TERRITORY BRIEF / NEW YORK','News That Matters','The news that matters to your accounts.', '<button class="primary" id="listen-news">▶ Listen to territory brief</button>')}<section class="edition-panel"><div><strong>September 25 edition</strong><p>${editionNotice()}</p></div>${badge('Sourced industry information','blue')}</section><div class="toolbar"><label class="filter-label">Territory<select id="news-territory">${['All New York','NYC','Hudson Valley','Capital Region','Central NY','Finger Lakes','Western NY'].map(t=>`<option ${t===newsTerritory?'selected':''}>${t}</option>`).join('')}</select></label><label class="filter-label">Topic<select id="news-topic">${['All topics',...new Set(MARKET_NEWS.map(n=>n.tag))].map(t=>`<option ${t===newsFilter?'selected':''}>${t}</option>`).join('')}</select></label><label class="background-toggle"><input id="news-background" type="checkbox" ${includeBackground?'checked':''}> Include older regional background</label></div><p class="fineprint">${rows.length} items · Statewide coverage applies across New York. Local items appear only where the source supports a location. Publication dates are shown separately from this edition’s review date.</p><div class="audio-controls"><button class="secondary" id="stop-news">■ Stop audio</button><span id="audio-status" role="status">Listen to the top three recent stories for this territory.</span></div><div class="news-grid">${rows.length?rows.map(n=>newsCard(n,true)).join(''):'<div class="empty">No verified items in this saved edition match these filters. Try another topic or include older background.</div>'}</div>`;}
function article(id){const n=MARKET_NEWS.find(n=>n.id===id);if(!n)return missing();return `<a href="#news" class="text-button">← Territory briefing</a><article class="article">${heading(n.tag.toUpperCase(),n.title,n.source+' · Published '+displayNewsDate(n.published))}<div class="notice">Sourced information · Reviewed Oct 6, 2026 · ${esc(n.regions.join(' / '))}${n.background?' · Older background':''}</div><section class="panel"><h2>What the source reports</h2><p>${esc(n.summary)}</p><a href="${n.url}" class="text-button" target="_blank" rel="noopener">Read the original source ↗</a>${n.extra?`<p><a href="${n.extra.url}" target="_blank" rel="noopener">${n.extra.label} ↗</a></p>`:''}<h2>Why it matters to a rep</h2><p>${esc(n.takeaway)}</p><p class="fineprint">QuickHits interpretation, separate from reported facts.</p><h2>Scope of this information</h2><p>${esc(n.scope)}</p><p class="fineprint">${editionNotice()}. Real industry news is separate from fictional account, menu and CRM records.</p></section></article>`;}
document.addEventListener('change',e=>{if(e.target.id==='news-territory'){newsTerritory=e.target.value;render();}if(e.target.id==='news-background'){includeBackground=e.target.checked;render();}});
document.addEventListener('click',e=>{if(e.target.closest('#listen-news'))speak(dailyNewsText(newsTerritory));if(e.target.closest('#stop-news'))stopAudio();});
