'use strict';
let micSession=null,micVersion=0,micNoteTarget=null;
const legacyStopListening=stopListening;
function micButton(text){const target=micSession?.target;const b=target?document.querySelector('[data-dictate="'+target+'"]'):(document.getElementById('speak-question')||document.getElementById('voice-button'));if(b)b.textContent=text;}
stopListening=function(){micVersion++;if(micSession){const s=micSession;micSession=null;clearTimeout(s.timer);clearInterval(s.levelTimer);s.abort?.abort();if(s.recorder?.state==='recording'){s.recorder.onstop=null;s.recorder.stop();}s.stream?.getTracks().forEach(t=>t.stop());s.audioContext?.close().catch(()=>{});}legacyStopListening();const inline=document.getElementById('voice-button');if(inline)inline.innerHTML=icon('mic')+' Speak';document.querySelectorAll('[data-dictate]').forEach(n=>n.textContent=n.dataset.voiceLabel||'Speak a note');};
function finishMic(){const s=micSession;if(!s||s.recorder?.state!=='recording')return;clearTimeout(s.timer);clearInterval(s.levelTimer);s.audioContext?.close().catch(()=>{});s.recorder.stop();s.stream.getTracks().forEach(t=>t.stop());listening=false;micButton('Transcribing…');voiceStatus('Got it. Turning that into text…');}
startListening=async function(){if(micSession){if(micSession.recorder?.state==='recording')finishMic();return;}if(liveBusy){voiceStatus('Let me finish this reply first.');return;}stopListening();stopAudio();const version=micVersion,noteTarget=micNoteTarget;micNoteTarget=null;micSession={target:noteTarget};micButton('Checking microphone…');await refreshOpenAI();if(version!==micVersion)return;if(!openAIState.connected){stopListening();voiceStatus('Voice input is not connected in this public demo. Please type your message or note.');return;}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){stopListening();voiceStatus('Recording isn’t supported here. Open this demo in Chrome or Edge, or type below.');return;}
try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:false});if(version!==micVersion){stream.getTracks().forEach(t=>t.stop());return;}const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(t=>MediaRecorder.isTypeSupported(t));if(!mime){stream.getTracks().forEach(t=>t.stop());throw Error('No supported recording format. Try Chrome or Edge.');}const recorder=new MediaRecorder(stream,{mimeType:mime,audioBitsPerSecond:64000}),chunks=[],s=micSession;Object.assign(s,{stream,recorder});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onerror=()=>{stopListening();voiceStatus('The microphone stopped. Try again or type below.');};recorder.onstop=async()=>{if(version!==micVersion)return;try{const blob=new Blob(chunks,{type:mime});if(blob.size<100)throw Error('I didn’t catch that. Try again.');const audio=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(blob);});if(version!==micVersion)return;s.abort=new AbortController();const r=await fetch('/api/transcribe',{method:'POST',headers:{'Content-Type':'application/json','X-QuickHits-Token':openAIState.csrf},body:JSON.stringify({audio,mime:mime.split(';')[0]}),signal:s.abort.signal});const result=await r.json();if(!r.ok)throw Error(result.error);if(version!==micVersion)return;const text=result.text.trim();stopListening();if(!text){voiceStatus('I didn’t catch any speech. Give it another try.');return;}if(noteTarget){const field=document.getElementById(noteTarget);if(field){field.value=(field.value?field.value+'\n':'')+text;field.dispatchEvent(new Event('input',{bubbles:true}));voiceStatus(noteTarget==='email-body'?'Added to your email. Review and edit it before opening Gmail.':'Added to your note. Review it, then save when you’re ready.');}return;}if(text.length>1000){document.getElementById('chat-input').value=text;voiceStatus('That was a long one. Shorten it in the text box, then send.');return;}await send(text);}catch(e){if(version===micVersion){stopListening();voiceStatus(e.message||'Couldn’t transcribe that. Try again.');}}};recorder.start();listening=true;micButton('Listening · tap to finish');voiceStatus('Go ahead. Pause when you’re done, or tap to finish. Up to 30 seconds.');s.timer=setTimeout(finishMic,30000);
// End the turn after audible speech followed by a quiet pause; no continuous listening.
try{const AudioCtx=window.AudioContext||window.webkitAudioContext;const ctx=new AudioCtx();s.audioContext=ctx;const analyser=ctx.createAnalyser();analyser.fftSize=2048;ctx.createMediaStreamSource(stream).connect(analyser);await ctx.resume();let lastSound=Date.now(),heard=false;const samples=new Uint8Array(analyser.fftSize);s.levelTimer=setInterval(()=>{if(micSession!==s||recorder.state!=='recording')return;analyser.getByteTimeDomainData(samples);let energy=0;for(const sample of samples)energy+=((sample-128)/128)**2;if(Math.sqrt(energy/samples.length)>0.018){heard=true;lastSound=Date.now();}if(heard&&Date.now()-lastSound>1800)finishMic();},100);}catch{/* Manual finish and 30-second limit remain available. */}
}catch(e){if(version===micVersion){stopListening();voiceStatus(e.name==='NotAllowedError'?'Microphone permission is off. Allow microphone access for this page, then try again.':e.name==='NotFoundError'?'No microphone found. Connect one, or type below.':e.message);}}};
window.addEventListener('pagehide',stopListening);

document.addEventListener('click',e=>{const b=e.target.closest('[data-dictate]');if(b){if(!micSession)micNoteTarget=b.dataset.dictate;startListening();}});

document.addEventListener('click',e=>{if(e.target.closest('[data-cancel-dictation]')){stopListening();voiceStatus('Recording cancelled. Your typed notes are still here.');}},true);
const activityDialog=document.getElementById('note-dialog');activityDialog.addEventListener('close',()=>{stopListening();document.getElementById('note-voice-status').textContent='Speak or type. Review your words before saving.';});activityDialog.addEventListener('cancel',stopListening);
document.addEventListener('change',e=>{if(e.target.id==='note-account'||e.target.id==='note-type'){stopListening();voiceStatus('Ready for your note.');}});
document.addEventListener('submit',e=>{if(e.target.id==='note-form'||e.target.id==='debrief-form')stopListening();},true);
document.addEventListener('input',e=>{if(e.target.matches('#note-text,#meeting-outcome,#meeting-action,#meeting-support')){const f=e.target;f.setCustomValidity(f.maxLength>0&&f.value.length>f.maxLength?'Please shorten this note to '+f.maxLength+' characters before saving.':'');}});

const emailVoiceDialog=document.getElementById('email-dialog');
emailVoiceDialog.addEventListener('close',()=>stopListening());
emailVoiceDialog.addEventListener('cancel',()=>stopListening());
