'use strict';
let openAIState={connected:false,csrf:''},liveBusy=false,liveRevision=0,liveAudio=null,liveAudioURL=null,audioFetch=null;
const demoSend=send,deviceSpeak=speak,deviceStop=stopAudio,crewAI=ai;
async function refreshOpenAI(){try{const r=await fetch('/api/voice-status');const status=r.ok?await r.json():{};openAIState={connected:status.connected===true,csrf:''};}catch{openAIState={connected:false,csrf:''};}const el=document.getElementById('openai-connection');if(el)el.innerHTML=connectionLabel();}
function connectionLabel(){return 'Prepared replies · '+(openAIState.connected?'AI-generated voice':'Browser voice');}
ai=function(){return crewAI().replace('<div class="eyebrow">','<p id="openai-connection" class="fineprint">'+connectionLabel()+'</p><div class="eyebrow">').replace('Prepared replies, no live AI or CRM connection.','When connected, OpenAI answers using demo accounts and saved notes. No live CRM or live news search.').replace('One tap to start. One question at a time in this demo.','One tap to start. Spoken replies use an AI-generated voice when connected.');};
stopAudio=function(){if(audioFetch){audioFetch.abort();audioFetch=null;}if(liveAudio){liveAudio.pause();liveAudio=null;}if(liveAudioURL){URL.revokeObjectURL(liveAudioURL);liveAudioURL=null;}deviceStop();};
speak=async function(text){if(!openAIState.connected)return deviceSpeak(text);stopListening();stopAudio();const seq=speechSequence,controller=new AbortController();audioFetch=controller;audioStatus('One sec…');try{const r=await fetch('/api/speech',{method:'POST',headers:{'Content-Type':'application/json','X-QuickHits-Token':openAIState.csrf},body:JSON.stringify({text:spokenCopy(text)}),signal:controller.signal});if(!r.ok){const e=await r.json();throw Error(e.error);}const blob=await r.blob();if(seq!==speechSequence)return;liveAudioURL=URL.createObjectURL(blob);liveAudio=new Audio(liveAudioURL);liveAudio.onended=()=>{if(seq===speechSequence)audioStatus('Anything else?');};await liveAudio.play();audioStatus('Speaking · OpenAI Coral · AI-generated voice');}catch(e){if(e.name!=='AbortError'&&seq===speechSequence)audioStatus('Audio unavailable. Your text reply is ready. '+(e.name==='NotAllowedError'?'Tap Listen again to play.':e.message));}finally{if(audioFetch===controller)audioFetch=null;}};
send=async function(q){q=q.trim();if(!q||liveBusy)return;await refreshOpenAI();if(!openAIState.connected)return demoSend(q);stopListening();stopAudio();const named=ACCOUNTS.filter(a=>q.toLowerCase().includes(a.name.toLowerCase())||q.toLowerCase().includes(a.id));if(named.length===1)selectedAccount=named[0].id;const a=ACCOUNTS.find(a=>a.id===selectedAccount),account=a.id,revision=liveRevision;const history=messages.filter(m=>m.account===account).slice(-8);messages.push({role:'user',text:q,account});liveBusy=true;render();audioStatus('Let me check…');try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json','X-QuickHits-Token':openAIState.csrf},body:JSON.stringify({question:q,history,context:{marketData:litAIContext(q),currentDate:new Date().toISOString().slice(0,10),demoSnapshotDate:'2026-10-06',account:a,sales:SALES[a.id]||null,salesPeriods:'Aug 29–Oct 6, 2026 versus prior 28 days; wholesale invoiced, not retail sell-through',lastVisit:visitBrief(a),notes:accountNotes(a).slice(0,5),competitors:competitorBrief(a),nextAction:a.action,demoSalesforceOpportunities:DEMO_SF_OPPORTUNITIES.filter(o=>o.account===a.id),demoCalendar:STOPS.filter(s=>s.id===a.id).map(s=>({...s,date:'2026-10-06',details:calendarMeta(s.id),source:'Synthetic Google Calendar example; not synced'})),followups:followupRows().filter(r=>r.account===a.id),news:territoryStories(a.region,false),newsEdition:NEWS_EDITION,newsNotLive:true}})});const result=await r.json();if(!r.ok)throw Error(result.error);if(revision!==liveRevision||selectedAccount!==account||location.hash!=='#ai')return;messages.push({role:'assistant',text:result.text,account});render();if(responseMode==='voice')speak(result.text);else audioStatus('Quiet mode · OpenAI reply ready.');}catch(e){if(revision===liveRevision&&location.hash==='#ai'){messages.push({role:'assistant',text:'Couldn’t get a live answer. '+e.message+' Your question has not been saved as a visit note.',account});render();audioStatus('Connection issue · try again.');}}finally{liveBusy=false;}};
document.addEventListener('change',e=>{if(e.target.id==='brief-account')liveRevision++;});
window.addEventListener('hashchange',()=>liveRevision++);
window.addEventListener('focus',refreshOpenAI);
refreshOpenAI();render();
